@ShoppingListAPI_HostAddress = http://localhost:5118

GET {{ShoppingListAPI_HostAddress}}/api/shopping-list/
Accept: application/json

###

POST {{ShoppingListAPI_HostAddress}}/api/shopping-list/
Content-Type: application/json

{
  "shoppingListName": "Weekly Groceries"
}

###

POST {{ShoppingListAPI_HostAddress}}/api/shopping-list/items
Content-Type: application/json

{
"shoppingListId": 2,
"productId": 14,
"quantity": 2,
"weight": 0.5,
"total": 3.47,
"isPickedUp": false
}

### 
GET {{ShoppingListAPI_HostAddress}}/api/shopping-list/items

###
POST {{ShoppingListAPI_HostAddress}}/api/shopping-list/products
Content-Type: application/json

{
"productName": "Glass Cleaner",
"price": 15.99
}

###

GET {{ShoppingListAPI_HostAddress}}/api/shopping-list/products